### ISSUE TITLE
Invalid textbox in AccName example

### ISSUE THREAD

**Issue by cookiecrook** [w3c/accname#131] opened 2021-06-03 17:38 UTC
https://w3c.github.io/accname/#example-2 includes the following:
```html
<div role="checkbox" aria-checked="false">Flash the screen <span role="textbox" aria-multiline="false"> 5 </span> times</div>
```

The embedded textbox is not focusable or marked as disabled. I'd recommend avoiding the textbox role entirely and use a number input instead, something like: 
```html
<input type="number" step="1" min="1" max="5" value="5">
```

**Comment by JAWS-test** [comment] 2021-06-03 19:35
Duplicate of https://github.com/w3c/accname/issues/65

**Comment by accdc** [comment] 2021-06-11 18:09
Since there is already a PR for this in #65 to address the issue, I'll close this issue so we can track it within the original as reported.

**Closed by accdc** 2021-06-11 18:09 UTC
